# Generated by Django 2.1.7 on 2021-01-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_timestamp', models.IntegerField(default=0)),
                ('reading', models.FloatField(default=0.0)),
                ('sensor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
