# Generated by Django 2.2 on 2021-02-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='reading_timestamp',
            field=models.FloatField(default=0),
        ),
    ]
