# Generated by Django 2.2 on 2021-02-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensorapp', '0002_auto_20210211_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
